name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

jobs:

  build_and_push:
    name: Build and push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            
    - name: Build docker image
      run: docker build -t $DOCKER_USER/$DOCKER_REPO:latest .
      
    - name: Push to dockerhub
      run: docker push $DOCKER_USER/$DOCKER_REPO:latest
